# Generated by Powerlevel10k configuration wizard on 2025-03-26 at 10:53 -03.
# Based on romkatv/powerlevel10k/config/p10k-pure.zsh, checksum 07533.
# Wizard options: powerline, pure, snazzy, rprompt, 24h time, 2 lines, sparse,
# instant_prompt=quiet.
# Type `p10k configure` to generate another config.
#
# Config file for Powerlevel10k with the style of Pure (https://github.com/sindresorhus/pure).
#
# Differences from Pure:
#
#   - Git:
#     - `@c4d3ec2c` instead of something like `v1.4.0~11` when in detached HEAD state.
#     - No automatic `git fetch` (the same as in Pure with `PURE_GIT_PULL=0`).
#
# Apart from the differences listed above, the replication of Pure prompt is exact. This includes
# even the questionable parts. For example, just like in Pure, there is no indication of Git status
# being stale; prompt symbol is the same in command, visual and overwrite vi modes; when prompt
# doesn't fit on one line, it wraps around with no attempt to shorten it.
#
# If you like the general style of Pure but not particularly attached to all its quirks, type
# `p10k configure` and pick "Lean" style. This will give you slick minimalist prompt while taking
# advantage of Powerlevel10k features that aren't present in Pure.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Prompt colors.
  local grey='242'
  local red='#FF5C57'
  local yellow='#F3F99D'
  local green='#5AF78E'
  local blue='#57C7FF'
  local magenta='#FF6AC1'
  local cyan='#9AEDFE'
  local white='#F1F1F0'

  # Left prompt segments.
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    os_icon                   # os identifier
    dir                       # current directory
    vcs                       # git status
    command_execution_time    # previous command duration (if >= 5s)
    # =========================[ Line #2 ]=========================
    newline                   # \n
    context                   # user@host (when relevant)
    virtualenv                # python virtual environment
    anaconda                  # conda environment
    pyenv                     # pyenv python version
    goenv                     # goenv go version
    nodenv                    # nodenv node version
    nvm                       # node version manager
    nodeenv                   # node virtual environment
    node_version              # node version
    background_jobs           # background jobs indicator
    prompt_char               # prompt symbol
  )

  # Right prompt segments.
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                    # exit code of the last command
    command_execution_time    # previous command duration
    history                   # history number
    time                      # current time
    # =========================[ Line #2 ]=========================
    newline                   # \n
  )

  # Basic style options that define the overall prompt look.
  typeset -g POWERLEVEL9K_BACKGROUND=                            # transparent background
  typeset -g POWERLEVEL9K_LEFT_WHITESPACE=                       # whitespace after left segments
  typeset -g POWERLEVEL9K_RIGHT_WHITESPACE=                      # whitespace before right segments
  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '          # separate left segments with a space
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '         # separate right segments with a space
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''              # no left segment separator
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''             # no right segment separator
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'  # show segment icons

  # Add an empty line before each prompt except the first. This doesn't emulate the bug
  # in Pure that makes prompt drift down whenever you use the Alt-C binding from fzf or similar.
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  # Magenta prompt symbol if the last command succeeded.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=$magenta
  # Red prompt symbol if the last command failed.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=$red
  # Default prompt symbol.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  # Prompt symbol in command vi mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  # Prompt symbol in visual vi mode is the same as in command mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='❮'
  # Prompt symbol in overwrite vi mode is the same as in command mode.
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false

  # Current directory - show full path, color by permission and write state.
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=$blue
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_DIR_SHORTEN_LEN=2
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
  # Show only the last two directory components by default.
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_with_folder_marker
  # Also shorten when directory is longer than this many characters.
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  # Show the full directory name when it's shorter than this many characters.
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  # Enable directory shortening in the left prompt.
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50

  # Context format when root: user@host. The first part white, the rest grey.
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE="%F{$white}%n%f%F{$grey}@%m%f"
  # Context format when not root: user@host. Show in cyan when SSH, grey otherwise.
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE="%F{$cyan}%n@%m%f"
  # Show context when root, in SSH, or when user is not default.
  # Uncomment the line below and set DEFAULT_USER to hide context when not needed.
  # typeset -g DEFAULT_USER='your-username'
  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_CONTENT_EXPANSION=
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$red

  # Show previous command duration only if it's >= 5s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5
  # Don't show fractional seconds. Thus, 7s rather than 7.3s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  # Duration format: 1d 2h 3m 4s.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
  # Yellow previous command duration.
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$yellow

  # Git prompt - show detailed status with colors.
  typeset -g POWERLEVEL9K_VCS_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_VCS_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='(^~|/mnt/|/media/)'
  
  # Git status icons and colors.
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=''
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
  typeset -g POWERLEVEL9K_VCS_TAG_ICON='tag'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
  
  # Git status colors.
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_STAGED_FOREGROUND=$green
  typeset -g POWERLEVEL9K_VCS_STAGED_BACKGROUND=
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_FOREGROUND=$red
  typeset -g POWERLEVEL9K_VCS_UNSTAGED_BACKGROUND=
  
  # Show ahead/behind indicators.
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣'
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGESFORMAT_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGESFORMAT_FOREGROUND=$magenta
  typeset -g POWERLEVEL9K_VCS_{COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=99
  
  # Git hooks to show status.
  typeset -g POWERLEVEL9K_VCS_GIT_HOOKS=(
    vcs-detect-changes
    git-untracked
    git-ahead-behind
    git-stash
    git-remotebranch
    git-tagname
  )
  
  # Show loading indicator.
  typeset -g POWERLEVEL9K_VCS_LOADING_TEXT='loading…'
  
  # Max sync latency - update promptly.
  typeset -g POWERLEVEL9K_VCS_MAX_SYNC_LATENCY_SECONDS=1
  
  # Show detailed git status with icons and colors.
  typeset -g POWERLEVEL9K_VCS_BACKEND=git

  # OS icon - show system identifier.
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$white
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=

  # Status - show exit code if non-zero.
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=$green
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✓'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$red
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

  # History - show history number.
  typeset -g POWERLEVEL9K_HISTORY_FOREGROUND=$grey
  typeset -g POWERLEVEL9K_HISTORY_BACKGROUND=

  # Background jobs - show if there are background jobs.
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=true
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=$yellow
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER}'

  # Node version - show current Node.js version.
  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # NVM - show Node Version Manager version.
  typeset -g POWERLEVEL9K_NVM_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NVM_BACKGROUND=
  typeset -g POWERLEVEL9K_NVM_SOURCES=(nvm nodebrew)

  # Virtualenv - show Python virtual environment.
  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=true
  typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=' '

  # Anaconda - show conda environment.
  typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=
  typeset -g POWERLEVEL9K_ANACONDA_SHOW_PYTHON_VERSION=true

  # Pyenv - show Python version from pyenv.
  typeset -g POWERLEVEL9K_PYENV_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_PYENV_BACKGROUND=
  typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)

  # Goenv - show Go version from goenv.
  typeset -g POWERLEVEL9K_GOENV_FOREGROUND=$cyan
  typeset -g POWERLEVEL9K_GOENV_BACKGROUND=

  # Nodenv - show Node version from nodenv.
  typeset -g POWERLEVEL9K_NODENV_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODENV_BACKGROUND=

  # Nodeenv - show Node virtual environment.
  typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=$green
  typeset -g POWERLEVEL9K_NODEENV_BACKGROUND=

  # Grey current time.
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$grey
  # Format for the current time: 09:51:02. See `man 3 strftime`.
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  # If set to true, time will update when you hit enter. This way prompts for the past
  # commands will contain the start times of their commands rather than the end times of
  # their preceding commands.
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  # Transient prompt works similarly to the builtin transient_rprompt option. It trims down prompt
  # when accepting a command line. Supported values:
  #
  #   - off:      Don't change prompt when accepting a command line.
  #   - always:   Trim down prompt when accepting a command line.
  #   - same-dir: Trim down prompt when accepting a command line unless this is the first command
  #               typed after changing current working directory.
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # Instant prompt mode.
  #
  #   - off:     Disable instant prompt. Choose this if you've tried instant prompt and found
  #              it incompatible with your zsh configuration files.
  #   - quiet:   Enable instant prompt and don't print warnings when detecting console output
  #              during zsh initialization. Choose this if you've read and understood
  #              https://github.com/romkatv/powerlevel10k#instant-prompt.
  #   - verbose: Enable instant prompt and print a warning when detecting console output during
  #              zsh initialization. Choose this if you've never tried instant prompt, haven't
  #              seen the warning, or if you are unsure what this all means.
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload allows you to change POWERLEVEL9K options after Powerlevel10k has been initialized.
  # For example, you can type POWERLEVEL9K_BACKGROUND=red and see your prompt turn red. Hot reload
  # can slow down prompt by 1-2 milliseconds, so it's better to keep it turned off unless you
  # really need it.
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
